#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lstepany <lstepany@student.hive.fi>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/04 11:09:27 by lstepany          #+#    #+#              #
#    Updated: 2020/06/04 11:30:12 by lstepany         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

#-*- MAKEFILE -*-

NAME = ft_display_file
CC = -Wall -Wextra -Werror
SRC = ft_display.c

all: $(NAME)
$(NAME) :
	gcc $(CC) -o $(NAME) $(SRC)
clean :
	rm -f *~
fclean : clean
	rm -f $(NAME)
re: fclean
	make	
